// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMnvvA-Z9hwPl0KYHSqumha7yhYNKtMS0',
    appId: '1:998358424854:web:3b478fc8edd8684d194437',
    messagingSenderId: '998358424854',
    projectId: 'auth-project-c941b',
    authDomain: 'auth-project-c941b.firebaseapp.com',
    storageBucket: 'auth-project-c941b.appspot.com',
    measurementId: 'G-D03N6CLJQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJzvfVU6k6CFF90rLT9OZQoCk9x6SRiAY',
    appId: '1:998358424854:android:b466bb08ca5b87a4194437',
    messagingSenderId: '998358424854',
    projectId: 'auth-project-c941b',
    storageBucket: 'auth-project-c941b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjGGFmLOFiHEzX4RBT0CyrPCbBdaB9tK8',
    appId: '1:998358424854:ios:ec0d7151ab10c063194437',
    messagingSenderId: '998358424854',
    projectId: 'auth-project-c941b',
    storageBucket: 'auth-project-c941b.appspot.com',
    androidClientId: '998358424854-3n11fs715i9nsqkjml6k5a8qp4co1f8u.apps.googleusercontent.com',
    iosClientId: '998358424854-9ci566i1oqd7mcef7cj2nscuq8fsig88.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase',
  );
}
